import Head from "next/head";
import React, { useEffect, useState } from "react";
import About4 from "../components/about/About4";
import Banner4 from "../components/banner/Banner4";
import Home4Blog from "../components/blog/Home4Blog";
import Home4Facilites from "../components/facilities/Home4Facilites";
import Footer from "../components/footer/Footer";
import Header4 from "../components/header/Header4";
import Preloader from "../components/loader/Preloader";
import Offer4 from "../components/offers/Offer4";
import RoomSuites4 from "../components/room/RoomSuites4";
import Service4 from "../components/services/Service4";
import Testimonial4 from "../components/testmonial/Testimonial4";
import Video4 from "../components/video/Video4";

function Index4() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 4000);
  }, []);
  return (
    <>
      {!loading ? (
        <Preloader />
      ) : (
        <>
          <Head>
            <title>
              Hotelina - Luxury Hotel and Suits Booking React NextJs Template
            </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/bg/sm-logo.png" />
          </Head>
          <Header4 />
          <Banner4 />
          <Home4Facilites />
          <About4 />
          <RoomSuites4 />
          <Service4 />
          <Offer4 />
          <Video4 />
          <Testimonial4 />
          <Home4Blog />
          <Footer />
        </>
      )}
    </>
  );
}

export default Index4;
